version: "3.7"

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      discovery.type: single-node
      LICENSE: basic
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      ES_PORT: ${ELASTICSEARCH_PORT}
      KIBANA_PORT: ${KIBANA_PORT}
    volumes:
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./es/data:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
    networks:
      static:
        ipv4_address: ${ELASTICSEARCH_HOST}
    healthcheck:
      test: curl http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT} || exit 1
      interval: 10s
      timeout: 10s
      retries: 50

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.8.0
    environment:
      ES_HOST: ${ELASTICSEARCH_HOST}
      ES_PORT: ${ELASTICSEARCH_PORT}
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - static
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      ELASTICSEARCH_HOSTS: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      ELASTICSEARCH_USERNAME: ${KIBANA_USERNAME}
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - static

  elastalert:
    container_name: elastalert
    image: jertel/elastalert2
    environment:
      ES_HOST: ${ELASTICSEARCH_HOST}
      ES_PORT: ${ELASTICSEARCH_PORT}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    volumes:
      - ./elastalert/config/config.yaml:/opt/elastalert/config.yaml
      - ./elastalert/rules/:/opt/elastalert/rules
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - static

networks:

  static:
    name: static
    ipam:
      config:
        - subnet: 172.20.0.0/16
